name: Terraform actions

on:
  push:
    branches:
      - main
  workflow_call: # allows calling this workflow from another workflow
    secrets:
      AWS_ACCESS_KEY_ID: { required: true }
      AWS_SECRET_ACCESS_KEY: { required: true }

permissions:
    id-token: write
    contents: read

jobs:
  tf_plan:
    name: terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: terraform init
        run: terraform init -upgrade -input=false -backend-config=./backend_config/config.s3.dev.tfbackend
        working-directory: ./terraform
      - name: terraform plan
        run: terraform plan
        working-directory: ./terraform
